name: ClassLoader
version: 0.1.10-alpha
main: vip.creatio.cloader.bukkit.CLoader
api-version: 1.13
depend: [CreatioBasic]
author: HenryRenYz
description: A Java development kit which allows you to load and unload class dynamically.
